### ISSUE TITLE
홈 화면 All places 커뮤니티 issue

### ISSUE THREAD

**Issue by leverest96** [team-economy/cracker-spring#51]
현재 홈 화면에서 All places 탭에서, 제목을 눌렀을 때 위치는 이동되나 커뮤니티로는 이동을 못하는 상황이에요.
My places 탭은 잘 작동됩니다.

**Comment by devpcjin** [comment]
아마 community랑 place객체 차이일 거에요 제가 내일 해결해서 PR 하겠습니다!
