### ISSUE TITLE
PK 노출 문제

### ISSUE THREAD

**Issue by devpcjin** [team-economy/cracker-spring#63]
현재 우리 페이지 접근할 때 PK (각 테이블 ID)를 사용하는데,
ex) `carckers.life/user/1` 이렇게 PK를 노출 시키면 아무래도 보안상의 문제가 있을 것 같아서 튜터님께 여쭤보니
해쉬처리를 하거나 이메일을 사용해야한다고 합니다.
유저는 그렇고 커뮤니티도 커뮤니티 아이디로 진행하게 되는데 해쉬처리를 하거나 아니면 커뮤니티 이름으로 url값을 바꿔야할 것 같습니다

**Comment by devpcjin** [comment]
참고로 인스타의 경우는 아이디이고
네이버의 경우 사용자는 아이디, 블로그 포스트는 해쉬처리돼있는것같네요.

**Comment by leverest96** [comment]
현재 user 페이지는 nickname으로 바꿨는데 community 페이지는 뭘로 가야할지 모르겠네요.
이름으로 가려고했는데 이름이 유일값이 아니게 될 것 같아서요
그래서 투표 부탁
1. 전화번호로 간다.
2. 다른 의견 ㅎㅎ

**Comment by devpcjin** [comment]
2. 주소 (도로명주소x)

**Comment by jin2424** [comment]
2. 맛집이름

**Comment by leverest96** [comment]
맛집이름은 중복이 가능해질 것 같아서요

**Comment by devpcjin** [comment]
ㅋㅋㅋㅋ 이름 유일값아니게 될것같다고 써있자나요 ㅠ

**Comment by leverest96** [comment]
community는 어차피 못 지워서 일단 community id값만 노출시키는 걸로 가게했어요

**Comment by yunicho** [comment]
전화번호는 null일수도 있어서 도로명이 데이터상으로는 말이 되는데 url에 addr가 보이는 것도 본 적 없긴 하네여 ㅎㅎ..

**Comment by jin2424** [comment]
UUID란
[https://mattmk.tistory.com/31](url) 
REST API 서버 개발 시 UUID 체계를 사용
[https://medium.com/aha-official/%EC%95%84%ED%95%98-rest-api-%EC%84%9C%EB%B2%84-%EA%B0%9C%EB%B0%9C-6-43568d94878a](url)
